import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { resumeAPI, rewriteAPI } from '../api';
import { Bot, Zap, Sparkles, Wand2, Copy, Check, ArrowLeft, AlertTriangle, Target, ArrowLeftRight, FileText, Download } from 'lucide-react';

import html2pdf from 'html2pdf.js';

export default function ResumeOptimizer() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [resumeData, setResumeData] = useState(null);
    const [targetRole, setTargetRole] = useState('');
    const [jobDescription, setJobDescription] = useState('');
    const [mode, setMode] = useState('ATS');
    const [rewrittenText, setRewrittenText] = useState('');
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState(false);
    const [warning, setWarning] = useState(null);
    const [downloading, setDownloading] = useState(false);
    const [viewMode, setViewMode] = useState('output'); // 'output', 'compare'

    useEffect(() => {
        const fetchResume = async () => {
            try {
                const res = await resumeAPI.getById(id);
                setResumeData(res.data);
                if (res.data?.predicted_role && res.data.predicted_role !== 'Analyzing...') {
                    setTargetRole(res.data.predicted_role);
                }
            } catch (err) {
                console.error(err);
            }
        };
        fetchResume();
    }, [id]);

    const handleRewrite = async () => {
        if (!targetRole.trim() && !jobDescription.trim()) {
            alert('Please enter a Target Role (e.g. "DevOps Engineer") or paste a Job Description.');
            return;
        }
        setLoading(true);
        setWarning(null);
        try {
            const alignmentContext = jobDescription.trim()
                ? `TARGET ROLE: ${targetRole}\n\nJOB DESCRIPTION:\n${jobDescription}`
                : targetRole.trim();

            const res = await rewriteAPI.transform(resumeData.content_text || resumeData.content, alignmentContext, mode);
            if (res.data.success) {
                setRewrittenText(res.data.rewritten_resume);
                setWarning(res.data.warning);
                setViewMode('compare'); // Auto-switch to comparison view
            } else {
                alert(res.data.error || 'Failed to transform resume.');
            }
        } catch (err) {
            console.error(err);
            alert('Service unavailable. Please check your AI keys.');
        } finally {
            setLoading(false);
        }
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(rewrittenText);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadAsPDF = async () => {
        const title = resumeData?.title || 'Resume';
        const role = targetRole || resumeData?.predicted_role || 'Optimized';
        
        setDownloading(true);
        
        const container = document.createElement('div');
        container.innerHTML = `
            <div style="font-family: 'Georgia', serif; font-size: 11pt; line-height: 1.7; color: #1a1a1a; padding: 40px 50px; max-width: 820px; margin: 0 auto; background: #ffffff;">
                <div style="text-align: center; border-bottom: 2px solid #2c3e50; padding-bottom: 14px; margin-bottom: 20px;">
                    <h1 style="font-size: 20pt; color: #1a1a1a; letter-spacing: 1px; margin: 0;">${title.toUpperCase()}</h1>
                    <p style="font-size: 9pt; color: #555; margin-top: 4px;">AI-Optimized for: ${role} &nbsp;|&nbsp; Generated by AI Resume Analyzer</p>
                </div>
                <div style="white-space: pre-wrap; word-wrap: break-word; font-size: 10.5pt; line-height: 1.75;">${rewrittenText.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
                <div style="margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; text-align: center; font-size: 8pt; color: #aaa;">
                    Generated by AI Resume Analyzer &bull; ${new Date().toLocaleDateString()}
                </div>
            </div>
        `;
        
        const opt = {
            margin:       10,
            filename:     `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${role.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`,
            image:        { type: 'jpeg', quality: 0.98 },
            html2canvas:  { scale: 2 },
            jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
        };

        try {
            await html2pdf().set(opt).from(container).save();
        } catch (error) {
            console.error("PDF generation failed:", error);
            alert("Failed to generate PDF. Please try again.");
        } finally {
            setDownloading(false);
        }
    };

    if (!resumeData) return (
        <div className="flex items-center justify-center min-h-[60vh]">
            <div className="flex flex-col items-center gap-4">
                <div className="animate-spin w-10 h-10 border-4 border-indigo-600 border-t-transparent rounded-full"></div>
                <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Loading Resume</p>
            </div>
        </div>
    );

    const originalText = resumeData.content_text || resumeData.content || '';

    return (
        <div className="space-y-8">
            {/* Header */}
            <div className="flex items-center justify-between border-b border-white/5 pb-6">
                <div>
                    <h1 className="text-4xl font-black tracking-tighter bg-gradient-to-r from-white to-slate-400 bg-clip-text text-transparent">
                        AI Resume Transformer
                    </h1>
                    <p className="text-slate-500 font-bold uppercase text-[10px] tracking-widest mt-1">
                        {resumeData.title} • {mode} Mode
                    </p>
                </div>
                <div className="flex gap-3">
                    <button onClick={() => navigate(-1)} className="px-5 py-2.5 rounded-xl bg-white/5 border border-white/10 text-xs font-black uppercase tracking-widest hover:bg-white/10 transition-all flex items-center gap-2">
                        <ArrowLeft size={14} /> Back
                    </button>
                    <button
                        onClick={handleRewrite}
                        disabled={loading}
                        className="px-6 py-2.5 rounded-xl bg-indigo-600 text-white text-xs font-black uppercase tracking-widest hover:bg-indigo-700 shadow-[0_0_20px_rgba(79,70,229,0.3)] transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                    >
                        {loading && <div className="w-3 h-3 border-2 border-white/20 border-t-white rounded-full animate-spin"></div>}
                        <Zap size={14} />
                        {loading ? 'Transforming...' : 'Transform'}
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Control Panel — Left Column */}
                <div className="lg:col-span-1 space-y-6">
                    {/* Target Role */}
                    <div className="glass-card p-6">
                        <label className="block text-[10px] font-black uppercase tracking-widest text-indigo-400 mb-2 px-1">
                            🎯 Target Role <span className="text-emerald-400">(Required)</span>
                        </label>
                        <p className="text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-3 px-1">
                            e.g. DevOps Engineer, Data Scientist
                        </p>
                        <select
                            className="w-full p-4 bg-black/40 border-2 border-indigo-500/30 rounded-xl text-sm text-white font-bold focus:ring-2 focus:ring-indigo-500/40 focus:border-indigo-500 outline-none transition-all cursor-pointer appearance-none"
                            value={targetRole}
                            onChange={(e) => setTargetRole(e.target.value)}
                        >
                            <option value="" className="bg-slate-900">Select Target Role</option>
                            <option value="Backend Developer" className="bg-slate-900">Backend Developer</option>
                            <option value="Frontend Developer" className="bg-slate-900">Frontend Developer</option>
                            <option value="Full Stack Developer" className="bg-slate-900">Full Stack Developer</option>
                            <option value="Data Scientist" className="bg-slate-900">Data Scientist</option>
                            <option value="DevOps Engineer" className="bg-slate-900">DevOps Engineer</option>
                            <option value="Machine Learning Engineer" className="bg-slate-900">Machine Learning Engineer</option>
                            <option value="Cloud Architect" className="bg-slate-900">Cloud Architect</option>
                            <option value="System Administrator" className="bg-slate-900">System Administrator</option>
                            <option value="Security Engineer" className="bg-slate-900">Security Engineer</option>
                            <option value="Product Manager" className="bg-slate-900">Product Manager</option>
                            <option value="UI/UX Designer" className="bg-slate-900">UI/UX Designer</option>
                        </select>
                    </div>

                    {/* JD */}
                    <div className="glass-card p-6">
                        <label className="block text-[10px] font-black uppercase tracking-widest text-indigo-400 mb-2 px-1">
                            Job Description <span className="text-slate-500">(Optional)</span>
                        </label>
                        <textarea
                            className="w-full h-36 p-4 bg-black/40 border border-white/5 rounded-xl text-sm text-slate-300 focus:ring-2 focus:ring-indigo-500/20 font-medium custom-scrollbar transition-all resize-none"
                            placeholder="Paste the full JD for precise keyword alignment..."
                            value={jobDescription}
                            onChange={(e) => setJobDescription(e.target.value)}
                        />
                    </div>

                    {/* Mode Selection */}
                    <div className="glass-card p-6">
                        <label className="block text-[10px] font-black uppercase tracking-widest text-indigo-400 mb-4 px-1">Strategy</label>
                        <div className="grid grid-cols-2 gap-3">
                            <button
                                onClick={() => setMode('ATS')}
                                className={`p-5 rounded-xl border-2 transition-all group flex flex-col gap-2 items-center text-center ${mode === 'ATS' ? 'border-indigo-600 bg-indigo-600/10' : 'border-white/5 bg-white/5 hover:border-white/10'}`}
                            >
                                <Zap size={22} className={mode === 'ATS' ? 'text-indigo-400' : 'text-slate-500'} />
                                <span className="font-black text-[10px] uppercase tracking-widest">ATS</span>
                            </button>
                            <button
                                onClick={() => setMode('Creative')}
                                className={`p-5 rounded-xl border-2 transition-all group flex flex-col gap-2 items-center text-center ${mode === 'Creative' ? 'border-indigo-600 bg-indigo-600/10' : 'border-white/5 bg-white/5 hover:border-white/10'}`}
                            >
                                <Sparkles size={22} className={mode === 'Creative' ? 'text-indigo-400' : 'text-slate-500'} />
                                <span className="font-black text-[10px] uppercase tracking-widest">Creative</span>
                            </button>
                        </div>
                    </div>
                </div>

                {/* Output Area — Right Column */}
                <div className="lg:col-span-2 glass-card p-1 border border-indigo-500/10 h-full min-h-[700px]">
                    <div className="bg-slate-900/40 rounded-xl h-full flex flex-col overflow-hidden">
                        {/* Output Header */}
                        <div className="p-5 border-b border-white/5 flex items-center justify-between">
                            <div className="flex items-center gap-3">
                                <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full animate-pulse"></div>
                                <h3 className="font-black text-sm uppercase tracking-widest text-white">
                                    {viewMode === 'compare' ? 'Before → After' : 'AI Output'}
                                </h3>
                            </div>
                            {rewrittenText && (
                                <div className="flex items-center gap-2">
                                    {/* View Toggle */}
                                    <button
                                        onClick={() => setViewMode(viewMode === 'compare' ? 'output' : 'compare')}
                                        className="px-3 py-1.5 bg-white/5 border border-white/10 hover:bg-indigo-600/10 hover:border-indigo-500/20 transition-all rounded-lg text-[10px] font-black uppercase tracking-widest text-slate-400 hover:text-indigo-400 flex items-center gap-1.5"
                                    >
                                        <ArrowLeftRight size={12} />
                                        {viewMode === 'compare' ? 'Full View' : 'Compare'}
                                    </button>
                                    <button
                                        onClick={copyToClipboard}
                                        className="px-3 py-1.5 bg-indigo-600/10 border border-indigo-500/20 hover:bg-indigo-600 transition-all rounded-lg text-[10px] font-black uppercase tracking-widest text-indigo-400 hover:text-white flex items-center gap-1.5"
                                    >
                                        {copied ? <><Check size={12} /> Copied</> : <><Copy size={12} /> Copy</>}
                                    </button>
                                    <button
                                        onClick={downloadAsPDF}
                                        disabled={downloading}
                                        className="px-3 py-1.5 bg-emerald-600/20 border border-emerald-500/30 hover:bg-emerald-600 transition-all rounded-lg text-[10px] font-black uppercase tracking-widest text-emerald-400 hover:text-white flex items-center gap-1.5 disabled:opacity-50"
                                    >
                                        {downloading ? (
                                            <><div className="w-2.5 h-2.5 border-2 border-emerald-500/30 border-t-emerald-400 rounded-full animate-spin"></div> Generating</>
                                        ) : (
                                            <><Download size={12} /> PDF</>
                                        )}
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* Content Area */}
                        <div className="flex-1 overflow-auto custom-scrollbar">
                            {!rewrittenText && !loading ? (
                                /* Empty State */
                                <div className="h-full flex flex-col items-center justify-center text-center space-y-6 opacity-20 p-10">
                                    <Bot size={80} className="text-slate-400" />
                                    <div>
                                        <p className="text-xs font-black uppercase tracking-[0.4em] text-slate-400 mb-2">Awaiting Signal</p>
                                        <p className="text-[10px] text-slate-500 font-medium">Set your target role and click Transform to begin</p>
                                    </div>
                                </div>
                            ) : loading ? (
                                /* Loading State */
                                <div className="h-full flex flex-col items-center justify-center text-center space-y-6 p-10">
                                    <div className="relative">
                                        <div className="w-16 h-16 border-4 border-indigo-600/10 border-t-indigo-500 rounded-full animate-spin"></div>
                                        <Bot size={28} className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-indigo-500" />
                                    </div>
                                    <div className="space-y-2">
                                        <p className="text-sm font-black uppercase tracking-widest text-white animate-pulse">Transforming Resume</p>
                                        <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Applying {mode} optimization • Gemini AI</p>
                                    </div>
                                </div>
                            ) : viewMode === 'compare' ? (
                                /* BEFORE / AFTER Comparison View */
                                <div className="flex flex-col h-full animate-fade-in">
                                    {warning && (
                                        <div className="mx-6 mt-4 bg-amber-500/5 border border-amber-500/20 p-4 rounded-xl flex items-start gap-3 text-amber-400 text-xs font-bold leading-relaxed">
                                            <AlertTriangle size={16} className="flex-shrink-0 mt-0.5" />
                                            <span>{warning}</span>
                                        </div>
                                    )}
                                    <div className="grid grid-cols-2 h-full divide-x divide-white/5">
                                        {/* BEFORE */}
                                        <div className="flex flex-col">
                                            <div className="p-4 border-b border-white/5 bg-rose-500/5">
                                                <div className="flex items-center gap-2">
                                                    <div className="w-2 h-2 bg-rose-500 rounded-full"></div>
                                                    <h4 className="text-[10px] font-black uppercase tracking-widest text-rose-400">Original</h4>
                                                </div>
                                            </div>
                                            <div className="flex-1 p-5 overflow-y-auto custom-scrollbar">
                                                <div className="text-slate-500 font-medium whitespace-pre-line leading-relaxed text-[12px]">
                                                    {originalText}
                                                </div>
                                            </div>
                                        </div>
                                        {/* AFTER */}
                                        <div className="flex flex-col">
                                            <div className="p-4 border-b border-white/5 bg-emerald-500/5">
                                                <div className="flex items-center gap-2">
                                                    <div className="w-2 h-2 bg-emerald-500 rounded-full"></div>
                                                    <h4 className="text-[10px] font-black uppercase tracking-widest text-emerald-400">AI Optimized</h4>
                                                </div>
                                            </div>
                                            <div className="flex-1 p-5 overflow-y-auto custom-scrollbar">
                                                <div className="text-slate-300 font-medium whitespace-pre-line leading-relaxed text-[12px]">
                                                    {rewrittenText}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            ) : (
                                /* Full Output View */
                                <div className="p-8 space-y-6 animate-fade-in">
                                    {warning && (
                                        <div className="bg-amber-500/5 border border-amber-500/20 p-4 rounded-xl flex items-start gap-3 text-amber-400 text-xs font-bold leading-relaxed">
                                            <AlertTriangle size={16} className="flex-shrink-0 mt-0.5" />
                                            <span>{warning}</span>
                                        </div>
                                    )}
                                    <div className="text-slate-300 font-medium whitespace-pre-line leading-loose text-sm p-8 bg-white/5 rounded-2xl border border-white/5 selection:bg-indigo-500/40">
                                        {rewrittenText}
                                    </div>
                                </div>
                            )}
                        </div>

                        <div className="p-4 border-t border-white/5 bg-black/20 text-center">
                            <span className="text-[9px] font-black text-slate-600 uppercase tracking-[0.4em]">AI Resume Analyzer • Powered by Gemini AI</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
